version: '3.7'
services:
  prisma:
    container_name: prisma
    build:
      context: prisma
      dockerfile: Dockerfile
    env_file:
      - .env.production
    command: ['prisma', 'studio']
    networks:
      - internal
      - web
    expose:
      - 5555

networks:
  web:
    external: true
  internal:
    external: true
